animals = ['bear', 'python', 'peacock', 'kangaroo', 'whale', 'platypus']

print "1. The animal at 1 is second (2nd) and is a python, right? ", animals[1]
print "2. The third (3rd) animal is at 2 and is a peacock, right? ", animals[2]
print "3. The first (1st) animal is at 0 and is a bear, right? ", animals[0]
print "4. The animal at 3 is the fourth (4th) and is a kangaroo, right? ", animals[3]
print "5. The fifth (5th) animal is at 4 and is a whale, right? ", animals[4]
print "6. The animal at 2 is the third (3rd) and is a peacock, right? ", animals[2]
print "7. The sixth (6th) animal is at 5 and is a platypus, right? ", animals[5]
print "8. The animal at 4 is the fifth (5th) and is a whale, right? ", animals[4]
